### ISSUE TITLE
geofence watcher doesn't work with polygon and circle filter

### ISSUE THREAD

**Issue by bertol83** [sirensolutions/enhanced_tilemap#114]
https://github.com/sirensolutions/kibi-internal/issues/11301

**Comment by dgilliga** [comment]
@bertol83 can you retest and close #11301 was fixed

**Comment by bertol83** [comment]
Using:
![image](https://user-images.githubusercontent.com/13969336/69790473-73a4f080-11ba-11ea-8d2d-def9468dafc8.png)

I still have the following Geo Fance script:

![image](https://user-images.githubusercontent.com/13969336/69790543-8e776500-11ba-11ea-91a7-370d1d6c4fdc.png)

and is still not working

**Comment by szydan** [comment]
@corrigancd could you please check this one Maybe the issue here is that it was NOT back-ported to 10.3.x If it works now please notify Nicola and close
